baseURL = 'https://schwesig.github.io/'
languageCode = 'en-us'
theme = "anatole"
enableEmoji = true

[params]
title = "Was Darf Satire"
author = "Thorsten Schwesig"
description = "Nicht erlaubt, nicht wichtig."