baseURL = 'https://schwesig.github.io/'
languageCode = 'en-us'
theme = "anatole"
enableEmoji = true

[params]
title = "Was Darf Satire"
author = "Thorsten Schwesig"
description = "Nicht erlaubt, nicht wichtig."
profilePicture = "images/profile.jpg"
copyright = "2022-{{ YEAR }}"

mainSections = ["blog"]

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:schwesig@gmx.de"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/schwesig"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/schwesig"

[[params.socialIcons]]
icon = "fa-solid fa-address-card"
title = "Address Card"
url = "https://prv.schwesig.net"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"